server:
  port: 8081

spring:
  application:
    name: "spring security oauth2(social login)"
  main:
    allow-circular-references: true # SecurityConfig 파일에서 커스텀 설정할때 빈의 순환참조가 일어나서 에러가 발생하는 현상 해결

  security:
    oauth2:
      client:
        registration:
          facebook: # https://developers.facebook.com/에서 프로젝트 만들고 아래 두 값을 얻어와야함
            # client-id에 커서를 두고 ctrl + b 를 누르면 해당 client-id와 client-secret이 어디로 바인딩이 되는지 알 수 있다.
            client-id: "1284893432313301"
            client-secret: "7bbcc67af4e86849634bee331c84f92c"
          google: # https://console.cloud.google.com/apis/dashboard에서 프로젝트 만들고 아래 두 값을 얻어와야함
            client-id: "71189845700-74p1velvvr0uc0i8sf5q1p3ggqq4dvr8.apps.googleusercontent.com"
            client-secret: "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"

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true # 서버를 재시작할때마다 엔티티가 생성된다.
    open-in-view: false
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3366/social # 3366은 docker-compose.yml에서 설정해둔 포트번호이다. social도 해당 파일에서 설정한 데이터베이스 파일 이름이다.
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver